embedding_size: 64
latent_embedding: 64

n_layers: 3
reg_weight: [0.1, 0.01, 0.001, 0.0001, 0.00001]
learning_rate: [1, 0.1, 0.01, 0.001, 0.0001]

# D-ISOLATOR param
gamma: [0.0001, 0.001, 0.01, 0.1, 1, 2] 

# U-ISOLATOR param
alpha: [2, 6, 8, 10]
beta: [1, 5, 10, 15, 20]
gamma_infer: [0.0001, 0.001, 0.01, 0.1, 1, 2] 


hyper_parameters: [ "gamma", "reg_weight", "learning_rate"]
# hyper_parameters: ["alpha", "beta", "gamma_infer", "gamma", "reg_weight", "learning_rate"]