recdim: 64
layer_num: 3
reg: [0.0001, 0.001, 0.01, 0.1] 

ssl_task: 'FAC'
learning_rate: [0.0001, 0.001, 0.01, 0.1] 

weight_decay: 1e-4
ssl_alpha: [0.01, 0.05, 0.1, 0.5, 1.0] 

ssl_temp: [0.1, 0.2, 0.5, 1.0] 

dropout_rate: 0.3
mm_fusion_mode: 'concat'
temp: 0.2
init: 'xavier'
adj_type: 'pre'

# D-ISOLATOR param
gamma: [0.0001, 0.001, 0.01, 0.1, 1, 2] 

# U-ISOLATOR param
alpha: [2, 6, 8, 10]
beta: [1, 5, 10, 15, 20]
gamma_infer: [0.0001, 0.001, 0.01, 0.1, 1, 2] 


hyper_parameters: ["gamma", "learning_rate", "ssl_temp", "ssl_alpha", "reg"]
# hyper_parameters: ["alpha", "beta", "gamma_infer", "gamma", "learning_rate", "ssl_temp", "ssl_alpha", "reg"]
