embedding_size: 64
reg_weight: [2.0, 1.0, 1e-01, 1e-02, 1e-03, 1e-04, 1e-05]

# D-ISOLATOR param
gamma: [0.0001, 0.001, 0.01, 0.1, 1, 2] 

# U-ISOLATOR param
alpha: [2, 6, 8, 10]
beta: [1, 5, 10, 15, 20]
gamma_infer: [0.0001, 0.001, 0.01, 0.1, 1, 2] 


hyper_parameters: ["reg_weight", "gamma"]
# hyper_parameters: ["alpha", "beta", "gamma_infer", "reg_weight", "gamma"]

