# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'clothing_with_pre.inter'

user_his_aver_text_feat: 'clothing_user_aver_history_item_text.npy'
user_his_aver_image_feat: 'clothing_user_aver_history_item_image.npy'

user_his_image_pre: 'clothing_user_history_image_pre.npy'
user_his_text_pre: 'clothing_user_history_text_pre.npy'


field_separator: "\t"
